// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	  int N = Integer.parseInt(args [0]); 
	  int below = 0;
	  int above = 0;

	 for(int i = 0; i < N; i++){
		double x = Math.random();
		if (x <= 0.5) {
		below++;
	}   else {
		above++; 
	}
}
    System.out.println("> 0.5: " + above + " times");
	System.out.println("<= 0.5: " + below + " times");

	if (above == 0 || below == 0) {
		System.out.println("");
	}
	else {
		double ratio = (double) above / below;
		System.out.println("ratio: " + ratio);
	}

	 }


	
}
